pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/orenevan/nice-exam/'
            }
        }
        stage('Deploy') {
            steps {
                sh 'cd terraform/webserver '
                sh 'cd terraform/webserver ; terraform init'
                sh 'cd terraform/webserver ; terraform plan '
                sh 'cd terraform/webserver ; terraform apply --auto-force'
                sh 'sleep 60'
                sh 'cd terraform/webserver ; terraform destory --auto-force'

            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}

