pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/orenevan/nice-exam/'
            }
        }
        stage('Deploy') {
            steps {
                sh 'cd terraform/webserver '
                sh 'terraform init'
                sh 'terraform plan '
                sh 'echo terraform apply tfplan'
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}

